module.exports = {
	TWT_GOTTWEET : "TWT_GOTTWEET",
	TWT_RENDEREDPIC : "TWT_RENDEREDPIC",
	IMG_REQUEST_RENDER : "IMG_REQUEST_RENDER",
	TWT_PIC_POSTED : "TWT_PIC_POSTED",
	TWT_DELETE : "TWT_DELETE",
	PAGE_UPDATE : "PAGE_UPDATE"
}